import streamlit as st
import random
import string

def generate_password(length, use_digits, use_special):
    characters = string.ascii_letters
    
    if use_digits:
        characters += string.digits

    if use_special:
        characters += string.punctuation  # adds special characters to the character string

    return ''.join(random.choice(characters) for _ in range(length))

st.title("Password Generator")

length = st.slider("Select password length", min_value=6, max_value=32, value=12)  # Fixed the typo and missing comma

use_digits = st.radiobutton("Include digits")

use_special = st.checkbox("Include special characters")

if st.button("Generate Password"):
    password = generate_password(length, use_digits, use_special)  # Fixed typo: changed 'lenght' to 'length'
    st.write(f"Generated Password: {password}")

    st.write("-------------")

    st.write("generated by vespera.")
